---
- name: Point iTerm2 at the repo-tracked prefs folder
  community.general.osx_defaults:
    domain: com.googlecode.iterm2
    key: PrefsCustomFolder
    type: string
    value: "{{ ansible_facts.env.HOME }}/.dotfiles/ansible/roles/macos/iterm2/prefs"
    state: present

- name: Enable loading (and saving) preferences from that folder
  community.general.osx_defaults:
    domain: com.googlecode.iterm2
    key: LoadPrefsFromCustomFolder
    type: bool
    value: true
    state: present

- name: Install Nerd Font used by iTerm2 profile
  ansible.builtin.get_url:
    url: https://github.com/ryanoasis/nerd-fonts/raw/refs/heads/master/patched-fonts/DroidSansMono/DroidSansMNerdFont-Regular.otf
    dest: "{{ ansible_facts.env.HOME }}/Library/Fonts/DroidSansMNerdFont-Regular.otf"
    mode: '0644'
