---

# Python virtual environment
- name: Install nodeenv/virtualenv via pip
  community.general.homebrew:
    name:
      - virtualenv
      - nodeenv
    state: present

- name: Create Python 3.12 virtual environment
  ansible.builtin.pip:
    name: []
    virtualenv: "{{ ansible_facts.env.HOME }}/virtualenv/venv"
    virtualenv_command: "virtualenv -p python3.14"


# Node.js and virtual environments idempotently
- name: Install nodeenv via pip
  ansible.builtin.pip:
    name: nodeenv
    state: present
- name: Create Node.js virtual environments
  ansible.builtin.command:
    cmd: "nodeenv {{ item.flag }} {{ ansible_facts.env.HOME }}/virtualnode/{{ item.name }}"
    creates: "{{ ansible_facts.env.HOME }}/virtualnode/{{ item.name }}/bin/node"
  loop:
    # - { name: 'venv10', flag: '--node=10.17.0' }
    # - { name: 'venv13', flag: '--node=13.14.0' }
    # - { name: 'venv20', flag: '--node=20.12.0' }
    # - { name: 'venv22', flag: '--node=22.11.0' }
    - { name: 'venv', flag: '' }  # use latest

- name: Install Python packages from requirements.txt
  ansible.builtin.pip:
    requirements: "{{ ansible_facts.env.HOME }}/.dotfiles/ansible/roles/macos/tasks/requirements_py.txt"
    executable: "{{ ansible_facts.env.HOME }}/virtualenv/venv/bin/pip"
